name: Deploy Azure Function - .NET 8 Isolated

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore FunctionAppProject/MyFunctionApp.csproj

      - name: Build application
        run: dotnet build FunctionAppProject/MyFunctionApp.csproj --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish FunctionAppProject/MyFunctionApp.csproj -c Release -o FunctionAppProject/publish

      - name: Deploy to Azure Functions using Publish Profile
        uses: Azure/functions-action@v1
        with:
          app-name: "func-mdmno-prod-sec-001"  # ✅ Ensure exact match
          package: "FunctionAppProject/publish"  # ✅ Deploy from correct directory
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-site-url: "https://func-mdmno-prod-sec-001.scm.azurewebsites.net"
